name: Push VL.Flex Nuget

on:
  push:
    branches:
      - master
    paths-ignore:
      - .editorconfig
      - .gitattributes
      - .github/**
      - .gitignore
      - LICENSE
      - README.md
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1
      
      - name: Setup Nuget.exe
        uses: nuget/setup-nuget@v1

      - name: Build VL.Flex
        run: |
          msbuild .\VL.Flex\src\VL.Flex.csproj -t:build -restore /property:Configuration=Release /property:Platform=x64

      - name: Publish VL Nuget
        uses: vvvv/PublishVLNuget@1.0.29
        with:
          nuspec: .nuget\VL.Flex.nuspec
          nuget-key: ${{ secrets.NUGET_KEY }}