name: Push VL.Flex.Skia Nuget

on:
  # push:
  #   branches:
  #     - master
  #   paths-ignore:
  #     - .editorconfig
  #     - .gitattributes
  #     - .github/**
  #     - .gitignore
  #     - LICENSE
  #     - README.md
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Nuget.exe
        uses: nuget/setup-nuget@v1

      - name: Publish VL Nuget
        uses: vvvv/PublishVLNuget@1.0.43
        with:
          nuspec: .nuget\VL.Flex.Skia.nuspec
          nuget-key: ${{ secrets.NUGET_KEY }}